version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    volumes:
      - ./deepfake_detector:/deepfake_detector  # 로컬 파일 동기화
