name: Django CI/CD

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub Actions의 체크아웃 작업
      - name: Checkout code
        uses: actions/checkout@v3

      # Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 필요한 종속성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint 및 테스트 실행
      - name: Run tests
        run: |
          python manage.py test

      # Base64로 저장된 PEM 키 디코딩
      - name: Decode PEM Key
        run: |
          echo "${{ secrets.PEM_KEY }}" | base64 -d > /tmp/deploy_key.pem
          chmod 600 /tmp/deploy_key.pem

      # 배포 스크립트 실행
      - name: Deploy to Server
        run: |
          ssh -i /tmp/deploy_key.pem -o StrictHostKeyChecking=no user@210.109.62.43 "cd /home/ubuntu/serialz/serialz-backend && docker-compose down && docker-compose up -d"
